spring:
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    schema-registry:
      url: http://localhost:8081
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/coupon?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 12345

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # 개발 환경에서는 update, 운영 환경에서는 validate 권장
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: false
server:
  port: 8090